### ISSUE TITLE
Missing alternative text for svg icon in the widget. 

### ISSUE THREAD

**Issue by padms** [FriendlyCaptcha/friendly-challenge#133]
Hi team, 
We would need an alternative text for the svg icon in the widget. Please find the image reference below.
![image](https://user-images.githubusercontent.com/52911293/187447835-983544ae-ccb7-4ce7-9d2b-6cf6ea1a50a6.png)

**Comment by gzuidhof** [comment]
This is definitely something we should improve and should be an easy fix. Thank you for opening this issue.

Currently we only have one icon that has an alternative text (in a `<title>` element within the SVG), for the icon when the widget is finished, as that one conveys real meaning, as it's a checkmark. That is handled inline [here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/dom.ts#L69) (`sr` is short for 'screen reader').

I would propose to add `aria-hidden="true"` to the other icons instead of giving them an alternative description. These are the icons:
* The shield with circle icon (as seen in the screenshot), visible before the verification is started.
* A spinner icon visible while the challenge is being solved.
* An error icon.

Each of these has enough text next to it that describes what's going on without needing the icon itself, so `aria-hidden="true"` seems like the way to go here.

Does that sound like the right solution here?

**Comment by padms** [comment]
Hi, Thanks for your reply. Sounds good to me. 👍
