### ISSUE TITLE
Http error code from errorCallback

### ISSUE THREAD

**Issue by alexbonair** [FriendlyCaptcha/friendly-challenge#134]
Hey there, 

In the docs (https://docs.friendlycaptcha.com/#/verification_api?id=verification-best-practices) 
it says to check for the http error code, but from errorCallback I do not get the code (at least for 400: sitekey_invalid).

Would be great to get the error code back, or do I miss something here?

Thanks and BR

**Comment by gzuidhof** [comment]
Hi Alex,

The errorCallback is something that is associated with the widget (i.e. it runs in your visitor's browser, and if the widget runs into an issue the function is called), whereas linked are the response codes and error codes for the verification API (called `siteverify`). 

our webserver will be talking to that API, so that would be code that runs in your server or is ran behind the scenes (e.g. in our Wordpress plugin). You should be able retrieve the HTTP response code in any programming language or request library you use for that. I hope that helps!
