### ISSUE TITLE
Drupal integration

### ISSUE THREAD

**Issue by jurgenhaas** [FriendlyCaptcha/friendly-challenge#153]
Hey all, very glad we found this project. It really looks as if this is the answer to a lot of spam and privacy issues. Thank you so much.

Together with a couple of other Drupal developers, we're planning to provide a Drupal integration. While discussing this, the question about the self-hosted FC server was raised, something most clients would ask for if they were privacy concerned. To avoid extra overhead for deployment and maintenance, the idea was raised to use the always existing Drupal server as the FC backend as well. It just seems a straightforward approach and reviewing the code at https://github.com/FriendlyCaptcha/friendly-lite-server we can't see any technical hurdle.

Before going any deeper, we wanted to run this idea by the FC maintainers to see what you think about the idea:

- is this a good idea from your perspective as well or, if not, why?
- is the friendly-lite-server the correct project for the selfhosted backend?
- as we would rewrite the backend to fit into the Drupal/Symfony framework, we wonder about long-term maintenance: if anything gets changed in the FC server, we would have to catch up with those changes and probably merge them into the Drupal solution. From the git history, the change frequency seems reasonable to allow that approach. Any thoughts on that?

Other than that, hope you like the idea. And if you had any further suggestions for a project like that, please let us know. We're happy to collaborate.

**Comment by dev-love** [comment]
Hi @jurgenhaas 

Thanks for your message! Happy to hear this!

There is already a Friendly Captcha module for Drupal, which is using the default approach of the FC backend as a service:
https://www.drupal.org/project/friendlycaptcha

Of course, it could make sense to use the already existing plugin since FC is free for non-commercial projects/websites.

For the basic use case of only spam prevention, the lite server could be used as well, so feel free to offer kind of a "Friendly Captcha Lite" module for Drupal as long is this plugin is and will remain free. For more security (especially risk/bot signals), the FC backend as a service would be needed, which is where the current Drupal module would make sense.
