### ISSUE TITLE
Unable to build from source (Unexpected token)

### ISSUE THREAD

**Issue by Connum** [FriendlyCaptcha/friendly-challenge#157]
I pulled this repo, did `npm install` and then tried to `npm build`, which resulted in the following error:

```
src/worker.ts → dist/worker.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
***/src/worker.ts (10:26)
 8: if (!Uint8Array.prototype.slice) {
 9:   Object.defineProperty(Uint8Array.prototype, "slice", {
10:     value: function (begin: number, end: number) {
                              ^
11:       return new Uint8Array(Array.prototype.slice.call(this, begin, end));
12:     },
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (***\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (***\node_modules\rollup\dist\shared\rollup.js:12555:16)
    at Module.tryParse (***\node_modules\rollup\dist\shared\rollup.js:12932:25)
    at Module.setSource (***\node_modules\rollup\dist\shared\rollup.js:12837:24)
    at ModuleLoader.addModuleSource (***\node_modules\rollup\dist\shared\rollup.js:22311:20)
```

Seems to me like there's something wrong with the rollup config not handling typescript?

**Comment by gzuidhof** [comment]
This indeed looks like rollup for some reason not wanting to interpret the file as typescript. I have not been able to reproduce this on my dev machine, maybe there is some global rollup version difference..

I'm sorry this doesn't provide a clear answer, I haven't looked into it yet in detail - I'll keep this issue open until someone figures out what the issue is here.

**Comment by Connum** [comment]
it was indeed an outdated global installation of rollup, thanks for the hint!
