### ISSUE TITLE
Allow to configure input name

### ISSUE THREAD

**Issue by franzwilding** [FriendlyCaptcha/friendly-challenge#16]
This would make the captcha way more flexible. At the moment I have to do something like this to make it work with Symfony forms (in Twig): 

```
<div class="frc-captcha" data-name="{{ full_name }}" data-sitekey="{{ siteKey }}" data-callback="onCaptcha"></div>
    <script>
        function onCaptcha(s) {
            var input = s.e.querySelector('input');
            input.setAttribute('name', s.e.dataset.name);
        };
    </script>
```

Also optionally setting the required attributed based on some config would be nice.

**Comment by gzuidhof** [comment]
I'm not sure I understand the request correctly:
Are you looking to override the name of the field that contains the solution,  changing it from `frc-captcha-solution` to something else. Is that something that is required by Symfony forms?

I am a bit hesitant to add this as it would complicate the documentation a bit, and the fix you came up with seems to solve it.
---

The reason the field is not `required` is because it is `hidden`, which means it can't be required. I considered removing the `hidden` tag and just hiding it with CSS somehow, but I fear what old browsers will do in that case. That's why I left it up to the implementer to block form submission if they wish.

**Comment by franzwilding** [comment]
That's exactly what I need. It could be an optional data attribute, so everyone who needs this can add it. Everyone else can just ignore it. 

I can imagine that this can be handy when working with different frameworks or CMS, not only Symfony in our case.

**Comment by gzuidhof** [comment]
Sure, I can add that :). I'll make it `data-solution-field-name`.

**Comment by franzwilding** [comment]
Super cool :-)

**Comment by gzuidhof** [comment]
Done, I pushed version 0.7.1 with support for this. I haven't tested this feature in ancient browsers yet, but I expect no issues.

Here's the relevant [documentation section](http://docs.friendlycaptcha.com/#/widget_api?id=data-solution-field-name).

**Comment by franzwilding** [comment]
👍
