### ISSUE TITLE
Captcha works with incorrect sitekey

### ISSUE THREAD

**Issue by Illia-Linevych** [FriendlyCaptcha/friendly-challenge#199]
Hi everyone! I found one strange behavior. When I add one random number or letter to the end of my sitekey, captcha solves the puzzle and correctly verifies the solution. But if I add more than one character to my sitekey, the captcha will stop working properly as expected. So is the first scenario a bug?

**Comment by Illia-Linevych** [comment]
I'm still waiting, so please reply. Thank you in advance

**Comment by gzuidhof** [comment]
Hi Illia,

The sitekey simply encodes your account ID and application ID together in base32hex. Adding a single character (or even two characters) generally does not result in a valid base32hex string - most implementations will ignore that extra character instead of rejecting it outright. I hope that answers your question. 

You can try playing around with it [here](https://cryptii.com/pipes/base32hex)
