### ISSUE TITLE
Language change bug in React

### ISSUE THREAD

**Issue by matapo** [FriendlyCaptcha/friendly-challenge#200]
Hello,

We encountered an issue that language is not changing in React while using your current example in documentation. Is it a bug or intended behaviour? Or are we implementing this library incorrectly?

Here is an interactive example: https://codesandbox.io/s/uc8gld

```
import { useEffect, useRef } from "react";
import { WidgetInstance } from "friendly-challenge";
import { useTranslation } from "react-i18next";

const FriendlyCaptcha = () => {
  const container = useRef<HTMLDivElement>(null);
  const widget = useRef<WidgetInstance>();

  const { i18n } = useTranslation();
  const language = i18n.language === "en" ? "en" : "de";

  const doneCallback = (solution: any) => {
    console.log("Captcha was solved. The form can be submitted.");
    console.log(solution);
  };

  const errorCallback = (err: any) => {
    console.log("There was an error when trying to solve the Captcha.");
    console.log(err);
  };

  useEffect(() => {
    if (!widget.current && container.current) {
      widget.current = new WidgetInstance(container.current, {
        startMode: "auto",
        doneCallback: doneCallback,
        errorCallback: errorCallback,
        language: language,
      });
    }

    return () => {
      if (widget.current !== undefined) widget.current.reset();
    };
  }, [container, language]);

  return (
    <div
      ref={container}
      className="frc-captcha"
      data-sitekey="DATA_SITEKEY"
      data-lang={language}
    />
  );
};

export default FriendlyCaptcha;
```

**Comment by gzuidhof** [comment]
Hi Matas,

I think you are using the library correctly - but this is a situation that the example code and/or the widget indeed does not handle as it perhaps should. Thank you a lot for the codesandbox link to reproduce the issue, that's really useful.

The language you set [only gets evaluated when the widget is first created](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/captcha.ts#L96-L108) (in other words: it happens in the constructor). In this React example we do not re-create the widget when the language changes, we only call `reset()`. In other words: once created a widget is assumed not to change language.

Two options here moving forward:
* We change the widget code so that it checks if the language changed when you call `reset()`, with that change no changes would be needed to the react code.
* You could re-create the widget if the language changes (perhaps calling `.destroy()` and setting `widget.current` to `undefined`) - I gave it a quick 5 minute shot, but my React hooks/`useEffect` intuition is rather basic. 

@merlinfuchs what do you think makes sense? I would generally bias towards the second (so we can keep the widget code simpler, and we can put some instructions in the docs for those who use React + dynamic language loading).

**Comment by matapo** [comment]
From what I understood so far, `.destroy()` method is somehow not compatible with React, since in strict dev mode it renders twice. Is it an issue wrap language set into a private method and re-use it in `.reset()`? I am happy to make a PR with some assistance.

**Comment by gzuidhof** [comment]
This is now possible in version `0.9.12` by calling `loadLanguage()` or `loadLanguage(languageCode)`. This loads the new language (checking the `data-lang` field, or with a language you pass in). 

Note that only the next displayed language will be in the new language, so if the widget is not active yet it probably makes sense to call `reset()` as well.

Happy to re-open this if you run into anything.

**Comment by matapo** [comment]
hi @gzuidhof,

The language is still not changing or I am not sure how to use it. Could you extend the codesandbox example with the new method?
