### ISSUE TITLE
[Question - best practice] How to receive a new token after subsequence requests

### ISSUE THREAD

**Issue by Anubarak** [FriendlyCaptcha/friendly-challenge#212]
Before this I only used Google-Recaptcha V3.
In Google Recaptcha you can fetch a new "secret" / "token" before each request without visual changes for the user.

The code will look like this
```JS
<script>
  function onClick(e) {
	e.preventDefault();
	grecaptcha.ready(function() {
	  grecaptcha.execute('reCAPTCHA_site_key', {action: 'submit'}).then(function(token) {
		  // Add your logic to submit to your backend server here.
	  });
	});
  }
</script>
```
This is just to explain where I'm coming from.

With your friendly-captcha there is no such way to retrieve the token **before** the request without visual changes for the user, so it's not a good way to "detroy" the field or reset the field before each request.

What else could I do to "renew" a token without user interactions / visual changes for users. My use case is the following:

- user starts to edit the form
- your captcha will validate everything -all good
- user submits your form with the valid token
- token is validated server side - all good
- there is an internal server error / some things could not be saved / an external endpoint is offline / some internal validations fail -> user receives an error message to re-submit the form or make changes in the form (no valid E-mail or whatever)
- user makes changes -> submits the form again
- now the token is not valid anymore

## my options now

1. cache the token server side and always let the same token pass (no good, someone could grab the token and still spam us)
2. call the `widget.reset()` function (not that well, because the visual effect kinda looks strange for users to validate the token again and again)

Are there any suggestions from you how to handle these scenarios? Is there any secret way to refresh the token without the visual reloading effect (I know it could lead to errors, but since I already have a valid token, I could grab some kind of re-freshtoken?)

Thank you very much

**Comment by gzuidhof** [comment]
Hi Robin,

I think I understand the question, let me know if I'm answering the wrong thing.

The short answer is that you would generally use `.reset()` here: a solution is only valid once. Generally the following flow:

* User submits the form (including a captcha)
* Server does validation that is cheap (e.g. checking max length of fields)
* Server checks the captcha (siteverify)
* Server performs the action (which may fail and require re-submission).

In most cases the user needing to restart the captcha is rare (unless it's a form where one is likely to make attempt after attempt, in which case maybe more of the checks could be moved in front of the captcha validation). 

Of course you know your own usecase the best - cacheing the token server side is an option, but indeed one could re-use it spam your server. You could also keep a counter per token and allow N attempts (and remove from this cache on successful submission).

Keeping it simple is in my opinion usually the best first option: I would advise to call `reset()`.

I hope that helps, let me know if something is unclear, otherwise I will close the issue if there are no further questions :).
