### ISSUE TITLE
API mocking in Playwright

### ISSUE THREAD

**Issue by pooledge** [FriendlyCaptcha/friendly-challenge#221]
I'm trying to test a form with a captcha, where programmatically enabling a submit button is not an option. I am mocking an API call to the FC endpoint and it works just fine:

```ts
await page.route(
	`${process.env.PUBLIC_CAPTCHA_ENDPOINT}?sitekey=${process.env.PUBLIC_CAPTCHA_SITEKEY}`,
	async (route) => {
		await route.fulfill({ json: { success: true } });
	}
);
```
 I can confirm it by manually envoking an API call and getting the desired response.

However, using standard Playwright's Chromium this API call is never being made, instead the widget shows the "Anti-robot-verification, Click here" right away, and when I click it, the infamous "Browser check failed, try a different browser" message arises.

Am I doing something wrong and how do I overcome this?

**Comment by gzuidhof** [comment]
This is a tricky situation - this automation is of course what the widget tries to prevent to some degree. There are some [basic](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/headless.ts#L21) checks, and if those fail no request is made at all - that also saves some usage from such bots.

The code snippet (i.e. the part to mock out with `{success: true}`) I think does not make sense in this setup. You would want to mock out the siteverify call, not the puzzle get call. In other words: this would happen on your backend server.

I know you state that programmatically enabling the submit button is not an option, could you explain why? My first intuition would be to use something like `page.evaluate` to enable the button. Of course the captcha check will fail (as it is literally a bot you are writing), but your tests can perhaps disable the captcha check otherwise.

I hope that helps!
