### ISSUE TITLE
[Question] What prevents a bot from solving the captcha?

### ISSUE THREAD

**Issue by Tummerhore** [FriendlyCaptcha/friendly-challenge#236]
I want to understand how Friendly captcha really works behind the scenes. I've already understood that it's based on a proof-of-work mechanism. So far so good. But what prevents a bot from solving the puzzle? Is it just the needed time for solving the puzzle and the hope is that it's too unattractive for bots to wait for the puzzle being solved? This sounds a bit too simple for me since the solving time is relatively short. It may be enough for simple brute force attacks, but for a promising credential stuffing attack, attackers may accept the extra time needed for captcha solving... But maybe I'm overseeing something here?

After looking into the dashboard, I noticed the "Smart Difficulty Scaling" option which sounds promising. The explanation says that the difficulty is increased for suspicious users. I guess a user is identified by things like IP address, user agent, ... here, right?

**Comment by gzuidhof** [comment]
Hi @Tummerhore,

Sorry for the late response - in a birds eye view you are correct: The difficulty is a deterence and the blocking mechanism - it adds a cost to the attacker. Our job as Friendly Captcha is to correctly estimate a risk score for a given visitior: How likely is this user to be abuse? If our signals indicate that this is likely, the proof-of-work challenge will be much more difficult. Instead of being able to submit thousands of forms per second, a spammer would need to spend XX seconds of compute per form - that changes the game completely.

**Comment by gzuidhof** [comment]
To add a

**Comment by Tummerhore** [comment]
Alright, thanks for the clarification. :)
