### ISSUE TITLE
Rough error message if the friendlycaptcha url is not reachable from client

### ISSUE THREAD

**Issue by ghenadiibatalski** [FriendlyCaptcha/friendly-challenge#25]
Hello, 

could you please change the error message below to something meaningful and also make it customizable for translation:

![image](https://user-images.githubusercontent.com/24528146/110758869-49f7c780-824d-11eb-8c53-2f9377e98bfe.png)

Such a problem normally should not occur but if it does, the error message could be more user friendly .

Thank you and regards,

**Comment by amenk** [comment]
We also ran into this problem. In our case there was a company network blocker in place which blocks access to 

https://eu-api.friendlycaptcha.eu/api/v1/puzzle?sitekey=....

If we open the API URL directly, we are presented with a page from the company network admins which allows to unblock the address and have a chance to continue working.

Please include the URL which was tried to fetch in the error message with the possibility to copy or open it, so that a enduser can find out what's going on.

**Comment by gzuidhof** [comment]
I see, could you expand a little on what a good error message would be in this case? I'm happy to change the widget to account for this situation, would this be a sufficient message?

```
Verification failed: Failed to retrieve puzzle from https://example.com/api/v1/puzzle?sitekey=....
<Raw JS error>
```

Of course the raw JS error will be hard to translate, but the first line we can add to our localizations.

**Comment by amenk** [comment]
The error message you suggest is fine (while I am not sure if the end user knows what's up with the "puzzle", so "failed to connect to ..." might be enough).
It's important that the URL can be clicked.
The RAW js error would not fit into the limited widget space, and be only helpful for developers, so it can be as well be printed with console.error only.

**Comment by ghenadiibatalski** [comment]
@gzuidhof hi, we need the possibility to replace those errors with a meaningful ones (eg. l10n)

**Comment by gzuidhof** [comment]
@ghenadiibatalski @amenk Could you have a look at #37 and let me know if these changes work for you? After that I'm happy to publish the next version :)

**Comment by amenk** [comment]
Looks good to me, thanks

**Comment by ghenadiibatalski** [comment]
@gzuidhof looks good, thank you!
