### ISSUE TITLE
Loading the v2 script breaks Angular JS 1.5.8

### ISSUE THREAD

**Issue by simonmargesin** [FriendlyCaptcha/friendly-challenge#278]
When loading the nomodule script @0.1.8 it seems like the script overwrites angular specific variables and breaks all mdDialogs that are beeing opened after loading the script. 
when calling $mdDialog.show, the dialog tries to load the js controller of the dialog and crashes immediately.

**Comment by K4n3dam4** [comment]
I can confirm similar issues, when using [Floating UI](https://github.com/floating-ui/floating-ui) with a loaded v2 site script. Your script seems to override ResizeObserver.toString function, causing it to return undefined instead of a string. Floating UI, expects the function to return a string, which is expected behavior.

**Comment by gzuidhof** [comment]
Thank you for letting us know, we'll look into this and hopefully fix it soon. If you learn anything along the way (e.g. a small example) that would help, but otherwise I think we'll manage to reproduce it with the above info already.

**Comment by K4n3dam4** [comment]
Thank you for your fast response, I managed to fix the compatibility issues with Floating UI by installing a newer version and am now checking my dependencies for other potential compatibility issues related to this prototype override. I'll keep you posted on my findings.

**Comment by gzuidhof** [comment]
This should be fixed with the new release `0.1.9`, with this PR https://github.com/FriendlyCaptcha/friendly-captcha-sdk/pull/16
