### ISSUE TITLE
Unable to import { WidgetInstance } from "friendly-challenge" #27

### ISSUE THREAD

**Issue by Affinity-Design** [FriendlyCaptcha/friendly-challenge#29]
I am using the latest NPM version of 7.3.0 of friendly-challenge. Continue to fail on importing via the following method. Im not sure if I am doing something wrong. I am using a react.js/ next.js setup. I'm assuming this is a syntax-related error from pulling es6 syntax pull into this node.js environment, just not sure how to resolve this. 

import { WidgetInstance } from "friendly-challenge";

Error message:
SyntaxError: Unexpected token 'export'
Source //

external%20%22friendly-challenge%22 (1:0) @ Object.friendly-challenge

1 | module.exports = require("friendly-challenge");

Uncaught at (file://D:\app\node_modules\friendly-challenge\index.js:534)

**Comment by dev-love** [comment]
Potential issue with NextJS?

**Comment by gzuidhof** [comment]
Apologies for the late reply, you're right that the issue is in ES Module loading. Most users of this library only import it clientside or use a bundler like Webpack or Rollup, but with Next.JS these modules will be loaded in your SSR build too (which is a plain Node environment). I'm not super familiar with Next.js I'm afraid: if it's possible to only load it for the clientside build that would solve it?

Maybe this package can help otherwise? https://www.npmjs.com/package/next-transpile-modules

**Comment by gzuidhof** [comment]
For anyone reading this: there is now an example Next.js integration available [here](https://github.com/FriendlyCaptcha/friendly-captcha-examples/tree/main/nextjs).
