### ISSUE TITLE
Publishing untranspiled ESM

### ISSUE THREAD

**Issue by aks-** [FriendlyCaptcha/friendly-challenge#39]
hey @gzuidhof! Currently you folks are publishing untranspiled ESM i.e. in index.js `export { WidgetInstance }`. This is problematic when we don't transpile in case of jest etc. I know there is workaround but that's something not the idle way I would say. Could this be please fixed?

And sorry to mention you directly. You could tell that we are in bit hurry :D

**Comment by gzuidhof** [comment]
Hi @aks-, no problem. I'm afraid this may be a `wontfix` on our end, the ESM choice is on purpose: it allows the subsequent build step to generally do a better job in minimizing when using a modern build tool like `rollup`, `vite` or `esbuild`, and it is the native format for the browser - which is the (only) intended target for the widget. 

I know the pain of fighting Jest to accept this kind of stuff though :(. Perhaps the easiest solution is to use Jest's `moduleNameMapper` to point at a dummy package?

**Comment by aks-** [comment]
hey just speaking out loud: hm but rollup violates the spec, esbuild is not production-ready yet, and i’m not sure about vite 🤦‍♂️. Also if the product requires those, then it's not actually targeting a browser, it’s targeting those tools, right? Additionally I think ESM should be in .mjs.  

apart from that in my experience CJS does identically as good a job as ES. could you please share some stats where we can see that it works better and by what margin?

Also doing `moduleNameMapper` or `transformIgnorePattern` feels hacky to certain degree to get one module working tbh

**Comment by gzuidhof** [comment]
Please could you change your tone to be less confrontational in future messages, I am only trying to help out and explain my reasoning :(.

> rollup violates the spec, esbuild is not production-ready yet 
I'm not sure how you came to this conclusion. Our NPM package follows the package.json description, see [here](https://nodejs.org/api/packages.html#packages_type): it instructs any tools to interpret `.js` files in the package as ES modules as defined in the specification, it is Jest that is the problem here.

ES Modules are supported natively in the browser, service workers (e.g. V8 serverless engines), Deno and are the standard moving forward in Node as well, the latest versions will accept them - albeit opt-in). CommonJS is still the standard format for Node right now, but the widget won't even work in Node: it relies on browser APIs and creates a webworker, the only reason it may be imported in a Node environment is in a test (through an indirect import) or in a SSR setup.

Adding a rule to those tools to ignore the file seems like the exact right way to approach this, using `moduleNameMapper` was literally created for this which makes it a suitable solution.

I don't see enough value in adding a `index.cjs` for a package that isn't intended to work for Node to save one line in a config file of a tool that is misbehaving. If you are dead set on solving it at the friendly-challenge level, you should be able to edit the rollup.config file and add a `index.cjs` target fairly easily.

**Comment by aks-** [comment]
@gzuidhof sorry if it came out wrong, I removed it, not sure how else to put it 🤦 English....

We will see what we can do 👍 thanks for explaination
