### ISSUE TITLE
Understanding GDPR and privacy

### ISSUE THREAD

**Issue by aks-** [FriendlyCaptcha/friendly-challenge#41]
Hey again @gzuidhof! I have a question: In the dev documentation there is EU endpoint description. I wonder how you folks use IP addresses and how is that complaint with GDPR.

Does the IP only sent on wire when the user is unable to identify as human or that would always be passed between friendly captcha and user-agent? What other sensitive info is passed around if any?

**Comment by gzuidhof** [comment]
Hi aks- :)

We don't send any potentially personally identifiable information regardless of the endpoint you use (do check out the request payload to see for yourself!). Along with every request in the browser a few headers will be sent along as well as the IP address. We aim to store as little as possible of course - and when we do store information we make sure it can't be traced back to an individual user or account. I think our incentives are aligned in that any data stored is a liability instead of an asset (unlike Google reCAPTCHA and friends).

The user only makes one request in the current set up: to request a puzzle. Any other requests (e.g. verification) will come from your server. Failure to verify will not originate from the end-user.

One of the signals that goes into our dynamic difficulty adjustment (= a premium feature you can toggle on) is the pattern of requests and their frequency. The IP address (prefix) is one of the best ways to distinguish between different users (although imperfect of course, it's still a useful signal). The idea here is that when a certain IP makes a ton of requests in a short timespan they get a puzzle that will take much longer to solve.

We hash any incoming IP addresses with a keyed hash and a sufficient salt for this purpose (so that they can't be reversed even if our datastore is ever compromised), and also this information (<hashed IP, behavior information>) is transient in nature.

The EU endpoint provides an endpoint (where this hashing takes place) that is hosted in Germany using a German DNS provider and data center (Hetzner), whereas the global endpoint is powered by Cloudflare (i.e. an American company). Cloudflare is an American company with POPs all over the world. 

So with the EU endpoint you can be sure that your end users talk to a German server only  - which was a feature that was asked for by our larger customers :). I hope that makes sense (sorry about the long answer).

**Comment by aks-** [comment]
Thank you for explaination, also that's what I thought by the term "IP address range" so saving more like "192.234.23.x" or "192.234.x.x".
