### ISSUE TITLE
Move inline styling to the stylesheet

### ISSUE THREAD

**Issue by papegaaij** [FriendlyCaptcha/friendly-challenge#53]
`getTemplate` in `dom.ts` contains 2 inline styles and `getPuzzle` in `puzzle.ts` contains another one. Not only do these inline styles make it harder to apply custom styling, they also conflict a possible Content-Security-Policy that forbids inline styles. It would be nice if these styles could be moved to `styles.css`.

**Comment by gzuidhof** [comment]
Sure, it's the right thing to do anyway :).

I published version `0.8.11` that has these inline styles moved over

**Comment by papegaaij** [comment]
Thanks! You may also want to move this one: https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/puzzle.ts#L60 For now, the happy flows are all fine.

**Comment by papegaaij** [comment]
I've hit a rather unfortunate snag in the current `getDoneHTML`. The `animate` tag on the inline SVG triggers CSP violations in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1675832 . For some reason Firefox implements some animations as direct modifications to the styling of the SVG elements and considers these modifications inline styling. For now, the only solution is to remove the animation or use CSS styling in `styles.css` to implement the fade-in.

**Comment by gzuidhof** [comment]
> Thanks! You may also want to move this one: https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/puzzle.ts#L60 For now, the happy flows are all fine.

Ah, I did a naive search only in `dom.ts`, I'll fix that in next release :).

> I've hit a rather unfortunate snag in the current getDoneHTML. The animate tag on the inline SVG triggers CSP violations in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1675832 . For some reason Firefox implements some animations as direct modifications to the styling of the SVG elements and considers these modifications inline styling. For now, the only solution is to remove the animation or use CSS styling in styles.css to implement the fade-in.

Ah.. that's a pain, as you could probably tell in `dom.ts` it's all string interpolation (mostly to keep the bundle size of the widget small). I'm happy to accept a PR that works around this issue (or I can take a stab at it, but that may only be next week..) 

I think the easiest solution is to remove the `animate` tag entirely, but unfortunately in the current re-used template system there is no way to pass an extra class for the icon. What we can do instead is add a `frc-done` class to the top-level component (`this.e` in the widget class) that gets added after the innerHTML is set. And add something in the `styles.css`:

```
.frc-done .frc-icon {
  /* fade in */
}
```

The reason I like this approach a bit better than setting a class on the icon itself is so that one can customize the styling further: one could change the outline of the entire widget to be green when it's done or something like that.

**Comment by papegaaij** [comment]
> What we can do instead is add a frc-done class to the top-level component (this.e in the widget class) that gets added after the innerHTML is set.

That sounds like an excellent solution. As our application also needs to operate in setups without internet connectivity, we need to package the js with our application, so for now I've just modified the minified js.

It's really unfortunate how Firefox treats these animations. Some animations work fine (like the `animateTransform`) and some properties can be animated (like width and height), but opacity breaks. However, looking at the activity on the bug report, I suspect it will take some time before this gets fixed.

**Comment by gzuidhof** [comment]
Perfect, let's do that then :). Even if Firefox fixes it, we aim to support pretty much any browser since 8 years (if I recall correctly), so the fix also has to work for currently broken Firefox :).

**Comment by gzuidhof** [comment]
Shipped! In version 0.8.12 the `animate` tag is gone, as well as the last remaining inline styles. Let me know if it now works out of the box :)

**Comment by papegaaij** [comment]
Yes, I can confirm that 0.8.12 works without any modifications. Thanks for the quick resolution! The only issue that remains with CSP is on Chrome about `unsafe-eval` (issue #46). You might want to take a look at the work around I found for that. This ticket can be closed.
