### ISSUE TITLE
Error: Endpoint not enabled

### ISSUE THREAD

**Issue by MauriceArikoglu** [FriendlyCaptcha/friendly-challenge#61]
When fetching the captcha on my local development server (localhost:3000) I receive the following error response:

Status 403 Forbidden
Response Body: `{"errors":["endpoint_not_enabled"]}`

The documentation doesn't state anything. so.. help please?!

The project is a next.js project, Widget is embedded in a react component and loaded dynamically to circumvent the SSR issues due to ES6.

**Comment by gzuidhof** [comment]
Hi Maurice,

I imagine it's because the endpoint you are using is not enabled for that application (sitekey). On the application management page you can check which endpoints you want to enable for it: either the global one (default), the EU-only endpoint, or both. 

The docs page for the EU-only endpoint can be found [here](https://docs.friendlycaptcha.com/#/eu_endpoint). Let me know if that helps!

**Comment by MauriceArikoglu** [comment]
Right, I realized once more I am stupid. Thanks.
