### ISSUE TITLE
Does FriendlyCaptcha offers an invisible mode?

### ISSUE THREAD

**Issue by bjoernbeckmann** [FriendlyCaptcha/friendly-challenge#70]
Is it possible to use FriendlyCaptcha in an invisible mode like google does in their reCaptcha implementation? Thx!

**Comment by gzuidhof** [comment]
Hi Bjoern,

Not really right now, technically you could hide the widget from the user and use the Javascript API to start it instead of a user interaction - but that is probably not what you mean.

We are actively thinking about this though, for our system it doesn't matter whether you solved the puzzle 30 minutes ago or right now. Also we could incorporate even more information into determining how difficult our puzzles should be if we can observe interaction behaviour in the background, without needing to resort to tracking users like reCAPTCHA does.

Anyway, that's in the mid-term future, for now the answer is more or less no.
