### ISSUE TITLE
Widget not shown on Safari browsers

### ISSUE THREAD

**Issue by dev-love** [FriendlyCaptcha/friendly-challenge#91]
One of our customers sent us the following potential bug report:

Dear Friendly Captcha Team,
we have been using your feature for our application forms (webforms) on our career website for a few months now. We have now seen that in the Safari browser (both iPad and MacBook) the Friendly Captcha box ("I am a human") does not appear at the end of the form as expected, but only a box with "Initialization". The form can still be filled out and submitted. According to our IT service provider, the captcha is executed on the backend side and the Friendly Captcha service is requested. So it is probably just a display problem of the widget. Is there anything known about this or can you help us somehow?

After a quick check, one of our team members was able to confirm this.

Could you please have a look at this and fix this or update this issue based on your findings?

**Comment by ReRi-Interlink** [comment]
Hi, please see the metioned screenshot attached
Thx! :)
<img width="1440" alt="Bildschirmfoto 2022-03-10 um 19 01 29 (2)" src="https://user-images.githubusercontent.com/101356426/157727278-0eb6b7b3-ffc4-403e-aa2a-d4f54fe5c96b.png">

**Comment by gzuidhof** [comment]
Do you maybe have more information around which device, OS and browser version was used?
Here's the debug page in Safari on my macbook (screenshot below, latest version of OS and Safari), which seems fine - maybe it's something that needs changing in the Wordpress plugin.

<img width="1322" alt="Screenshot 2022-03-10 at 19 51 20" src="https://user-images.githubusercontent.com/1039510/157734480-2510bd44-2e6a-4dfc-8a2e-f1f8d9d68853.png">

**Comment by gzuidhof** [comment]
Here it is in a simulator in Safari 8.0 on an iPhone 6 (2014). The user experience isn't great (browser freezes isn't responsive while solving), but it is usable..

We don't really support Safari versions before that, but it seems to work on Safari 7 (and maybe older): it shows an error, but then on pressing retry it works - but I never see it finish as the virtual device timeouts.

I know this isn't that helpful for the issue at hand, but I am hopeful it kind of rules out an issue within the widget. It could be something in the middle though: Wordpress plugins minifying the JS in a safari-unfriendly way.

**Comment by ReRi-Interlink** [comment]
Hi there,

we received the following information by our customer:

"As I could see from the discussion of the developers in github, one suspects that it is due to an old Safari version or a problem with the wordpress plugin.

 

We would like to inform you that our website (karriere-in-mv.de) does not use wordpress (but is based on PHP in the Fat Free Framework). We were able to determine the problem on our end devices with the following configurations:

 

MacBook Pro (2021, 16") macOS Monterey 12.2.1, Safari 15.3 (17612.4.9.1.8)

iPad Air (4th generation) iPadOS 15.3.1

iPad Pro (1st generation) iPadOS 14.3.1

iPhone SE (2nd) iOS 15.3.1

 

Hope this helps with troubleshooting. I appreciate feedback should the problem need to be looked for on our end after all."

I tested It with my MacBook Air (M1 2020) MacOS Monterey Version 12.0.1 and had the same issue.

Hopte this helps
Thx! Have a great weekend!

**Comment by merlinfuchs** [comment]
I can reproduce the issue on the most recent Safari version on https://karriere-in-mv.de/stelle/4363/bewerben. 

What seems to fail is creating loading the worker code:
<img width="923" alt="grafik" src="https://user-images.githubusercontent.com/33966852/157877292-85ed7352-5766-44ac-8448-d89aa81f0db7.png">
<img width="559" alt="grafik" src="https://user-images.githubusercontent.com/33966852/157877248-2e9ed579-ad6e-4b84-8d30-d0be10d901e9.png">

I would guess this is somehow related to the `Content-Security-Policy` on karriere-in-mv.de.

**Comment by merlinfuchs** [comment]
Adding `child-src blob:;` to the `Content-Security-Policy` seems to fix it.
The full element would then be:
```html
<meta
      http-equiv="Content-Security-Policy"
      content="child-src blob:; default-src 'self' 'unsafe-inline' *.googleapis.com *.googletagmanager.com *.friendlycaptcha.eu *.cookiebot.com *.google-analytics.com *.gstatic.com; img-src * 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googleapis.com unpkg.com *.cookiebot.com *.googletagmanager.com *.google-analytics.com blob:"
    />
```
